### ISSUE TITLE
Retrieving the manifest for an official Docker image (without the library prefix) causes a 500 error instead of a 401 error.

### ISSUE THREAD

**Issue by matzegebbe** [docker/distribution-library-image#146]
We are using the registry as a pull-through cache, as described here: https://docs.docker.com/registry/recipes/mirror/, for our Renovate bot. The bot does HTTP calls for manifests with digests like http://docker-registry-mirror.kube-system.svc.cluster.local:5000/v2/openjdk/manifests/sha256:8e17383576d7e71988ee5927473a32e8461381c7a29eefa9a0c24b3a28926272. Since openjdk is an official Docker image, the vendor prefix (library) is missing. The HTTP response for that call is a 500 error with the following message:
```bash
curl -I http://localhost:5000/v2/openjdk/manifests/sha256:8e17383576d7e71988ee5927473a32e8461381c7a29eefa9a0c24b3a28926272 
-> HTTP/1.1 500 Internal Server Error
```
```json
{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"errors":[{"code":"DENIED","message":"requested access to the resource is denied"},{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Action":"pull","Class":"","Name":"openjdk","Type":"repository"}]}]}}]}
```
doing the call with the `/library/` return the manifest as expected:
```bash
curl -I http://localhost:5000/v2/library/openjdk/manifests/sha256:8e17383576d7e71988ee5927473a32e8461381c7a29eefa9a0c24b3a28926272
-> HTTP/1.1 200 OK
```
while the offical docker registry gives a 401 

```bash
# not working 401 
TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:openjdk:pull" | jq -r .token)
curl -I -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -X GET https://registry-1.docker.io/v2/openjdk/manifests/sha256:8e17383576d7e71988ee5927473a32e8461381c7a29eefa9a0c24b3a28926272
# working 200
TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/openjdk:pull" | jq -r .token)
curl -I -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -X GET https://registry-1.docker.io/v2/library/openjdk/manifests/sha256:8e17383576d7e71988ee5927473a32e8461381c7a29eefa9a0c24b3a28926272
```

**I think a 500er error is wrong in that case and the UNAUTHORIZED registry should return a 401**

error message in renovate:
```yaml
        "message": "Response code 500 (Internal Server Error)",
         "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/opt/buildpack/tools/renovate/34.157.1/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/34.157.1 (https://github.com/renovatebot/renovate)",
             "accept": "application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "http://docker-registry-mirror.kube-system.svc.cluster.local:5000/v2/openjdk/manifests/sha256:8e17383576d7e71988ee5927473a32e8461381c7a29eefa9a0c24b3a28926272",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "HEAD",
           "http2": false
         },
         "response": {
           "statusCode": 500,
           "statusMessage": "Internal Server Error",
           "body": "",
           "headers": {
             "content-type": "application/json; charset=utf-8",
             "docker-distribution-api-version": "registry/2.0",
             "x-content-type-options": "nosniff",
             "date": "Wed, 08 Mar 2023 11:06:54 GMT",
             "content-length": "290",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
```
